name: compass
description: "Where is north?"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
